django_tweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweet_app.urls')),
    path('', include("django.contrib.auth.urls")),
]

tweet_app/urls.py
from django.urls import path
from . import views

app_name = "tweet_app"


urlpatterns = [
    path('', views.list_tweet, name="list_tweet"),          # www.atilsamancıoğlu.com/tweet_app
    path('add_tweet', views.add_tweet, name="add_tweet"),   # www.atilsamancıoğlu.com/tweet_app/add_tweet
    path('addtweetbyform', views.addtweetbyform, name='addtweetbyform'),
    path('addtweetbymodelform', views.addtweetbymodelform, name='addtweetbymodelform'),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('delete_tweet/<int:id>', views.delete_tweet, name="delete_tweet"),
]

tweet_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message = models.CharField(max_length=100)

    def __str__(self):
        return f"Tweet nick: {self.username} message: {self.message}"

tweet_app/forms.py
from django import forms
from django.forms import ModelForm
from tweet_app.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname", max_length=50)
    message_input = forms.CharField(label="Message", max_length=100, 
                                    widget=forms.Textarea(attrs={"class":"tweet_message"}))


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["username", "message"]

tweet_app/views.py
from django.shortcuts import render, redirect
from  . import models
from django.urls import reverse, reverse_lazy
from tweet_app.forms import AddTweetForm, AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

# Create your views here.

def list_tweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dictionary = {"tweets":all_tweets}
    return render(request, 'tweet_app/list_tweet.html', context=tweet_dictionary)

@login_required(login_url="/login")
def add_tweet(request):
    #print(request.POST)
    if request.POST:
        message = request.POST["message"]
        
        # tweet = models.Tweet(nickname,message)
        # tweet.save()

        models.Tweet.objects.create(username=request.user, message=message)
        return redirect(reverse('tweet_app:list_tweet'))
    else:
        return render(request, 'tweet_app/add_tweet.html')
    
def addtweetbyform(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(username=request.user, message=message)
            return redirect(reverse('tweet_app:list_tweet'))
        else:
            print("Error in form!")
            return render(request,'tweet_app/addtweetbyform.html',context={"form":form}) 
    else:
        form = AddTweetForm
        return render(request,'tweet_app/addtweetbyform.html',context={"form":form})


def addtweetbymodelform(request):
    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname"]
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweet_app:list_tweet'))
        else:
            print("Error in form!")
            return render(request,'tweet_app/addtweetbymodelform.html',context={"form":form}) 
    else:
        form = AddTweetModelForm()
        return render(request,'tweet_app/addtweetbymodelform.html',context={"form":form})

@login_required
def delete_tweet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('tweet_app:list_tweet')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{% static 'tweet_app/custom_form.css' %}">
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tweet_app:list_tweet' %}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweet_app:list_tweet' %}">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:add_tweet' %}">Add Tweet</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:addtweetbyform' %}">Add Tweet By Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:addtweetbymodelform' %}">Add Tweet By Model Form</a>
              </li>
              -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:signup' %}">Signup</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

    {% block content %}



    {% endblock %}

</body>
</html>

tweet_app/templates/tweet_app/add_tweet.html
{% extends 'base.html' %}

{% block content %}


<h1 class="container" style="width: 30%;">Add Tweet Page</h1>
<br>
<form action="" method="POST">
  {% csrf_token %}
  <div class="container" style="width: 50%;">
    <!--
    <div class="mb-3">
      <label for="
      " class="form-label">Nickname</label>
      <input type="text" class="form-control" id="nickname" name="nickname">
    </div>
    -->
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </div>
</form>


{% endblock %}

tweet_app/templates/tweet_app/addtweetbyform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="container">Add Tweet By Form Page</h1>
<br>
<div class="container tweet_form">
    
    <form action="" method="POST">
        {% csrf_token %}
        
        {% for field in form %}
        <div class="mb-3">
            {{field.label_tag}}
            {{field}}
        </div>
        {% endfor %}
    
        <button type="submit" class="btn btn-primary">Send Tweet</button>

    </form>
</div>


{% endblock %}

tweet_app/templates/tweet_app/addtweetbymodelform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="container">Add Tweet By Model Form Page</h1>
<div class="container tweet_form">
    <form action="" method="POST">
        {% csrf_token %}
        
    {% for field in form %}
    <div class="mb-3">
        {{field.label_tag}}
        {{field}}
    </div>
    {% endfor %}
    
    <button type="submit" class="btn btn-primary">Send Tweet</button>

    </form>
</div>



{% endblock %}

tweet_app/templates/tweet_app/list_tweet.html
{% extends 'base.html' %}

{% block content %}


    <div class="container" style="width: 50%;">
    {% for tweet in tweets %}
        <div class="card" style="padding: 10px">
            <div class="card-header" style="background-color: cornflowerblue;">
                <h4>{{tweet.username}}</h4>
            </div>
            <div class="card-body">
                <p class="card-text">{{tweet.message}}</p>
            </div>
            {% if tweet.username == user %}
            <a href="{% url 'tweet_app:delete_tweet' id=tweet.id %}" class="btn btn-danger">Sil</a>
            {% endif %}

        </div>
    {% endfor %}
    </div>


{% endblock %}